name: Deploy to EC2

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files and create .env on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd fundmate-be
          git pull origin main

          cat > .env <<EOL
          API_GATEWAY_PORT=3000
          AI_SERVICE_PORT=3001
          AUTH_SERVICE_PORT=3002
          FUNDING_SERVICE_PORT=3003
          INTERACTION_SERVICE_PORT=3004
          PAYMENT_SERVICE_PORT=3005
          PUBLIC_SERVICE_PORT=3006
          USER_SERVICE_PORT=3007
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_PORT=3306
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          EOL

          sudo docker system prune -a --volumes  
          sudo docker-compose down
          sudo docker-compose up -d --build
          EOF
