name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci --legacy-peer-deps --verbose

      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint test build
